# datum -- GENERATED by tools/gen_ports.py from tools/derive.py -- do not edit by hand.
# source this (or append the flags to FZF_DEFAULT_OPTS). ANSI indices
# mean it follows the terminal's datum theme automatically.
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=fg:-1,bg:-1,hl:4,fg+:-1,bg+:0,hl+:4,info:8,border:0,separator:0,prompt:5,pointer:4,marker:2,spinner:6,header:8,gutter:-1"
