# datum -- GENERATED by tools/gen_ports.py from tools/derive.py -- do not edit by hand.
# source from ~/.zshrc (or ~/.bashrc for the ls parts). ANSI indices
# follow the terminal's datum theme automatically.

# ls: BSD (macOS) uses LSCOLORS, GNU uses LS_COLORS.
export CLICOLOR=1
export LSCOLORS='exGxfxdxFxdxdxbxbxexbx'
export LS_COLORS='di=34:ln=96:so=35:pi=33:ex=95:bd=33:cd=33:su=31:sg=31:tw=34:ow=31:mi=31:or=31:*.tar=91:*.tgz=91:*.zip=91:*.gz=91:*.bz2=91:*.xz=91:*.7z=91:*.rar=91:*.jpg=35:*.jpeg=35:*.png=35:*.gif=35:*.svg=35:*.webp=35:*.mp4=35:*.mov=35:*.mp3=35:*.md=32:*.txt=32:*.json=33:*.yml=33:*.yaml=33:*.toml=33'

# zsh-syntax-highlighting (if installed). fn calls = magenta(call),
# strings = green, paths = var(11), keywords = blue, errors = red.
if [ -n "$ZSH_VERSION" ]; then
  typeset -gA ZSH_HIGHLIGHT_STYLES
  ZSH_HIGHLIGHT_STYLES[command]='fg=13'
  ZSH_HIGHLIGHT_STYLES[builtin]='fg=13'
  ZSH_HIGHLIGHT_STYLES[function]='fg=13'
  ZSH_HIGHLIGHT_STYLES[alias]='fg=13'
  ZSH_HIGHLIGHT_STYLES[precommand]='fg=13'
  ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=4'
  ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=2'
  ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=2'
  ZSH_HIGHLIGHT_STYLES[path]='fg=11'
  ZSH_HIGHLIGHT_STYLES[globbing]='fg=9'
  ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=12'
  ZSH_HIGHLIGHT_STYLES[comment]='fg=8'
  ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=1'
fi
