#!/usr/bin/env python3
"""Generate per-app colour ports from the derived palette.

The palette in derive.py is the source of truth. Every port here is generated
from it, so a port cannot silently drift out of sync with the scheme (which is
exactly how a stale purple survived in the hand-written Ghostty theme).

    python3 tools/gen_ports.py          # write ports/
    python3 tools/gen_ports.py --check  # fail if ports/ is stale (CI-friendly)

Ports written:
    ports/ghostty/datum-dark, ports/ghostty/datum-light
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from derive import palette  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ANSI slot -> palette role.
#   normal 1-6 = tier-1 accents; bright 9-14 carry the colours ANSI otherwise
#   cannot reach: orange (no slot of its own) and the tier-2 pastels, so the
#   loud/quiet tier system is available to any 16-colour CLI tool.
ANSI = {
    0: "bg2",  8: "fg1",
    1: "red",  9: "orange",
    2: "green", 10: "green",
    3: "yellow", 11: "var",
    4: "blue", 12: "op",
    5: "purple", 13: "call",
    6: "cyan", 14: "param",
    7: "fg0", 15: "fg0",
}
# 0/7/15 want the neutral ramp rather than a literal role, per mode.
NEUTRAL_OVERRIDE = {
    "dark":  {0: "#2b2f35", 7: "#dbe0e8", 15: "#eef2f7"},
    "light": {0: "#292e35", 7: "#ced3d9", 15: "#e7ecf2"},
}

GHOSTTY_HEADER = """\
# datum {mode} -- GENERATED by tools/gen_ports.py, do not edit by hand.
# Source of truth: tools/derive.py (OKLCH spec + contrast/CVD verification).
#
# normal slots 1-6 = tier-1 accents (saturated reference points).
# bright slots 9-14 carry orange + the tier-2 pastels, so the loud/quiet tier
# system reaches any 16-colour CLI tool.{note}
"""

LIGHT_NOTE = """
# On the light ground the tier-2 glue is *darker* than tier-1 (it is the body
# text, so it holds the higher contrast) -- here "bright" means more prominent,
# not lighter. That is the theme's logic, not an accident."""


def ghostty(mode):
    p = palette(mode)
    ov = NEUTRAL_OVERRIDE[mode]
    out = [GHOSTTY_HEADER.format(mode=mode, note=LIGHT_NOTE if mode == "light" else "")]
    out.append(f'background = {p["bg0"]["hex"]}')
    out.append(f'foreground = {p["fg0"]["hex"]}')
    out.append(f'cursor-color = {p["purple"]["hex"]}')
    out.append(f'cursor-text = {p["bg0"]["hex"]}')
    out.append(f'selection-background = {p["bg2"]["hex"]}')
    out.append(f'selection-foreground = {p["fg0"]["hex"]}')
    out.append("")
    for slot in range(16):
        hexv = ov.get(slot) or p[ANSI[slot]]["hex"]
        out.append(f"palette = {slot}={hexv}")
    return "\n".join(out) + "\n"


PORTS = {
    "ports/ghostty/datum-dark": lambda: ghostty("dark"),
    "ports/ghostty/datum-light": lambda: ghostty("light"),
}


def main():
    check = "--check" in sys.argv
    stale = []
    for rel, render in PORTS.items():
        path = os.path.join(ROOT, rel)
        content = render()
        current = None
        if os.path.exists(path):
            with open(path) as fh:
                current = fh.read()
        if check:
            if current != content:
                stale.append(rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(content)
        print(("unchanged " if current == content else "wrote     ") + rel)
    if check:
        if stale:
            print("STALE (re-run tools/gen_ports.py): " + ", ".join(stale))
            return 1
        print("all ports up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
