#!/usr/bin/env python3
"""Generate per-app color ports from the derived palette.

The palette in derive.py is the source of truth. Every port here is generated
from it, so a port cannot silently drift out of sync with the scheme (which is
exactly how a stale purple survived in the first hand-written Ghostty theme).

    python3 tools/gen_ports.py          # write ports/
    python3 tools/gen_ports.py --check  # fail if ports/ is stale (CI-friendly)

Terminals and editors get separate dark/light files (they can't follow the OS
on their own). Shell/CLI tools that run *inside* a terminal are emitted once,
using ANSI color indices (0-15) so they inherit the terminal's datum theme and
follow light/dark automatically.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from derive import palette  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODES = ("dark", "light")


def pal(mode):
    return {k: v["hex"] for k, v in palette(mode).items()}


# ANSI slot -> palette role. normal 1-6 = tier-1 accents; bright 9-14 carry the
# colors ANSI otherwise can't reach: orange (no slot of its own) + the tier-2
# glue, so the loud/quiet tier system reaches any 16-color tool.
ANSI = {1: "red", 9: "orange", 2: "green", 10: "green", 3: "yellow", 11: "var",
        4: "blue", 12: "op", 5: "purple", 13: "call", 6: "cyan", 14: "param",
        8: "fg1"}
NEUTRAL = {
    "dark":  {0: "#2b2f35", 7: "#dbe0e8", 15: "#eef2f7"},
    "light": {0: "#292e35", 7: "#ced3d9", 15: "#e7ecf2"},
}


def ansi16(mode):
    p = pal(mode)
    return [NEUTRAL[mode].get(i) or p[ANSI[i]] for i in range(16)]


GEN = "GENERATED by tools/gen_ports.py from tools/derive.py -- do not edit by hand."

# ---------------------------------------------------------------- ghostty
def ghostty(mode):
    p, a = pal(mode), ansi16(mode)
    note = ""
    if mode == "light":
        note = ("\n# On the light ground the tier-2 glue is darker than tier-1 (it is the body\n"
                "# text, so it holds the higher contrast) -- here 'bright' means more prominent.")
    lines = [f"# datum {mode} -- {GEN}{note}",
             f"background = {p['bg0']}", f"foreground = {p['fg0']}",
             f"cursor-color = {p['purple']}", f"cursor-text = {p['bg0']}",
             f"selection-background = {p['bg2']}", f"selection-foreground = {p['fg0']}", ""]
    lines += [f"palette = {i}={a[i]}" for i in range(16)]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- alacritty (TOML)
def alacritty(mode):
    p, a = pal(mode), ansi16(mode)
    n, b = a[0:8], a[8:16]
    q = lambda h: f'"{h}"'  # noqa: E731
    return (
        f"# datum {mode} -- {GEN}\n"
        "[colors.primary]\n"
        f"background = {q(p['bg0'])}\nforeground = {q(p['fg0'])}\n\n"
        "[colors.cursor]\n"
        f"cursor = {q(p['purple'])}\ntext = {q(p['bg0'])}\n\n"
        "[colors.selection]\n"
        f"background = {q(p['bg2'])}\ntext = {q(p['fg0'])}\n\n"
        "[colors.normal]\n"
        f"black = {q(n[0])}\nred = {q(n[1])}\ngreen = {q(n[2])}\nyellow = {q(n[3])}\n"
        f"blue = {q(n[4])}\nmagenta = {q(n[5])}\ncyan = {q(n[6])}\nwhite = {q(n[7])}\n\n"
        "[colors.bright]\n"
        f"black = {q(b[0])}\nred = {q(b[1])}\ngreen = {q(b[2])}\nyellow = {q(b[3])}\n"
        f"blue = {q(b[4])}\nmagenta = {q(b[5])}\ncyan = {q(b[6])}\nwhite = {q(b[7])}\n"
    )


# ---------------------------------------------------------------- kitty (conf)
def kitty(mode):
    p, a = pal(mode), ansi16(mode)
    lines = [f"# datum {mode} -- {GEN}",
             f"background {p['bg0']}", f"foreground {p['fg0']}",
             f"cursor {p['purple']}", f"cursor_text_color {p['bg0']}",
             f"selection_background {p['bg2']}", f"selection_foreground {p['fg0']}",
             f"url_color {p['blue']}", ""]
    lines += [f"color{i} {a[i]}" for i in range(16)]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------- wezterm (TOML scheme)
def wezterm(mode):
    p, a = pal(mode), ansi16(mode)
    arr = lambda xs: "[" + ", ".join(f'"{x}"' for x in xs) + "]"  # noqa: E731
    return (
        f"# datum {mode} -- {GEN}\n"
        f"# Drop in ~/.config/wezterm/colors/ ; select with color_scheme = 'datum-{mode}'\n"
        "[colors]\n"
        f'foreground = "{p["fg0"]}"\nbackground = "{p["bg0"]}"\n'
        f'cursor_bg = "{p["purple"]}"\ncursor_fg = "{p["bg0"]}"\ncursor_border = "{p["purple"]}"\n'
        f'selection_bg = "{p["bg2"]}"\nselection_fg = "{p["fg0"]}"\n'
        f"ansi = {arr(a[0:8])}\nbrights = {arr(a[8:16])}\n\n"
        "[metadata]\n"
        f'name = "datum-{mode}"\n'
    )


# ---------------------------------------------------------------- tmux (ANSI, theme-following)
def tmux_theme():
    return (
        f"# datum -- {GEN}\n"
        "# source-file this from ~/.tmux.conf. Uses ANSI indices so it follows\n"
        "# the terminal's datum theme (and light/dark) automatically.\n"
        'set -g status-style "bg=default,fg=color8"\n'
        'set -g status-left ""\n'
        'set -g status-right "#[fg=color8] #S "\n'
        'set -g window-status-format "#[fg=color8] #I:#W "\n'
        'set -g window-status-current-format "#[fg=color4,bold] #I:#W "\n'
        'set -g pane-border-style "fg=color0"\n'
        'set -g pane-active-border-style "fg=color4"\n'
        'set -g mode-style "bg=color0,fg=color7"\n'
        'set -g message-style "bg=color0,fg=color3"\n'
        'set -g message-command-style "bg=color0,fg=color3"\n'
    )


# ---------------------------------------------------------------- fzf (ANSI, theme-following)
def fzf_theme():
    opts = ("--color=fg:-1,bg:-1,hl:4"
            ",fg+:-1,bg+:0,hl+:4"
            ",info:8,border:0,separator:0"
            ",prompt:5,pointer:4,marker:2,spinner:6,header:8,gutter:-1")
    return (
        f"# datum -- {GEN}\n"
        "# source this (or append the flags to FZF_DEFAULT_OPTS). ANSI indices\n"
        "# mean it follows the terminal's datum theme automatically.\n"
        f'export FZF_DEFAULT_OPTS="${{FZF_DEFAULT_OPTS:-}} {opts}"\n'
    )


# ---------------------------------------------------------------- delta (git pager, ANSI-named)
def delta_theme():
    return (
        f"# datum -- {GEN}\n"
        "# add `[include] path = <this file>` to ~/.gitconfig. Named colors\n"
        "# resolve to ANSI, so it follows the terminal's datum theme.\n"
        "[delta]\n"
        "    line-numbers = true\n"
        "    minus-style = red\n"
        "    minus-emph-style = bold red\n"
        "    plus-style = green\n"
        "    plus-emph-style = bold green\n"
        "    line-numbers-minus-style = red\n"
        "    line-numbers-plus-style = green\n"
        '    line-numbers-zero-style = "#8f98a3"\n'
        "    hunk-header-style = blue bold\n"
        '    hunk-header-decoration-style = "#2b2f35" box\n'
        "    file-style = magenta bold\n"
        '    file-decoration-style = "#2b2f35" ul\n'
    )


# ---------------------------------------------------------------- shell (ls + zsh-syntax-highlighting)
def shell_theme():
    return (
        f"# datum -- {GEN}\n"
        "# source from ~/.zshrc (or ~/.bashrc for the ls parts). ANSI indices\n"
        "# follow the terminal's datum theme automatically.\n\n"
        "# ls: BSD (macOS) uses LSCOLORS, GNU uses LS_COLORS.\n"
        "export CLICOLOR=1\n"
        "export LSCOLORS='exGxfxdxFxdxdxbxbxexbx'\n"
        "export LS_COLORS='di=34:ln=96:so=35:pi=33:ex=95:bd=33:cd=33:su=31:sg=31:tw=34:ow=31:mi=31:or=31"
        ":*.tar=91:*.tgz=91:*.zip=91:*.gz=91:*.bz2=91:*.xz=91:*.7z=91:*.rar=91"
        ":*.jpg=35:*.jpeg=35:*.png=35:*.gif=35:*.svg=35:*.webp=35:*.mp4=35:*.mov=35:*.mp3=35"
        ":*.md=32:*.txt=32:*.json=33:*.yml=33:*.yaml=33:*.toml=33'\n\n"
        "# zsh-syntax-highlighting (if installed). fn calls = magenta(call),\n"
        "# strings = green, paths = var(11), keywords = blue, errors = red.\n"
        'if [ -n "$ZSH_VERSION" ]; then\n'
        "  typeset -gA ZSH_HIGHLIGHT_STYLES\n"
        "  ZSH_HIGHLIGHT_STYLES[command]='fg=13'\n"
        "  ZSH_HIGHLIGHT_STYLES[builtin]='fg=13'\n"
        "  ZSH_HIGHLIGHT_STYLES[function]='fg=13'\n"
        "  ZSH_HIGHLIGHT_STYLES[alias]='fg=13'\n"
        "  ZSH_HIGHLIGHT_STYLES[precommand]='fg=13'\n"
        "  ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=4'\n"
        "  ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=2'\n"
        "  ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=2'\n"
        "  ZSH_HIGHLIGHT_STYLES[path]='fg=11'\n"
        "  ZSH_HIGHLIGHT_STYLES[globbing]='fg=9'\n"
        "  ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=12'\n"
        "  ZSH_HIGHLIGHT_STYLES[comment]='fg=8'\n"
        "  ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=1'\n"
        "fi\n"
    )


# ---------------------------------------------------------------- vscode (JSON theme)
def vscode(mode):
    p = pal(mode)
    a = ansi16(mode)
    ui = {
        "editor.background": p["bg0"], "editor.foreground": p["fg0"],
        "editorCursor.foreground": p["purple"],
        "editor.selectionBackground": p["bg2"],
        "editor.lineHighlightBackground": p["bg1"],
        "editorLineNumber.foreground": p["bg2"],
        "editorLineNumber.activeForeground": p["fg1"],
        "editorWhitespace.foreground": p["bg2"],
        "editorIndentGuide.background1": p["bg1"],
        "editorIndentGuide.activeBackground1": p["bg2"],
        "editorWidget.background": p["bg1"], "editorWidget.border": p["bg2"],
        "editorHoverWidget.background": p["bg1"],
        "editorSuggestWidget.background": p["bg1"],
        "editorSuggestWidget.selectedBackground": p["bg2"],
        "editorError.foreground": p["red"], "editorWarning.foreground": p["orange"],
        "editorInfo.foreground": p["blue"],
        "editorBracketMatch.background": p["bg2"], "editorBracketMatch.border": p["blue"],
        "activityBar.background": p["bg0"], "activityBar.foreground": p["fg0"],
        "activityBar.inactiveForeground": p["fg1"],
        "activityBarBadge.background": p["blue"], "activityBarBadge.foreground": p["bg0"],
        "sideBar.background": p["bg1"], "sideBar.foreground": p["fg0"],
        "sideBarTitle.foreground": p["fg1"],
        "sideBarSectionHeader.background": p["bg1"],
        "list.activeSelectionBackground": p["bg2"], "list.activeSelectionForeground": p["fg0"],
        "list.hoverBackground": p["bg1"], "list.inactiveSelectionBackground": p["bg1"],
        "list.highlightForeground": p["blue"],
        "statusBar.background": p["bg1"], "statusBar.foreground": p["fg1"],
        "statusBar.noFolderBackground": p["bg1"],
        "statusBarItem.remoteBackground": p["blue"], "statusBarItem.remoteForeground": p["bg0"],
        "titleBar.activeBackground": p["bg0"], "titleBar.activeForeground": p["fg0"],
        "titleBar.inactiveBackground": p["bg0"], "titleBar.inactiveForeground": p["fg1"],
        "editorGroupHeader.tabsBackground": p["bg1"],
        "tab.activeBackground": p["bg0"], "tab.activeForeground": p["fg0"],
        "tab.inactiveBackground": p["bg1"], "tab.inactiveForeground": p["fg1"],
        "tab.activeBorderTop": p["blue"], "tab.border": p["bg1"],
        "panel.background": p["bg0"], "panel.border": p["bg2"],
        "panelTitle.activeForeground": p["fg0"], "panelTitle.inactiveForeground": p["fg1"],
        "input.background": p["bg1"], "input.foreground": p["fg0"], "input.border": p["bg2"],
        "dropdown.background": p["bg1"], "dropdown.foreground": p["fg0"],
        "button.background": p["blue"], "button.foreground": p["bg0"],
        "badge.background": p["blue"], "badge.foreground": p["bg0"],
        "focusBorder": p["blue"], "foreground": p["fg0"],
        "widget.shadow": "#00000040",
        "scrollbarSlider.background": p["bg2"] + "80",
        "scrollbarSlider.hoverBackground": p["bg2"] + "b0",
        "minimap.selectionHighlight": p["blue"],
        "gitDecoration.modifiedResourceForeground": p["yellow"],
        "gitDecoration.deletedResourceForeground": p["red"],
        "gitDecoration.untrackedResourceForeground": p["green"],
        "gitDecoration.ignoredResourceForeground": p["fg1"],
        "terminal.background": p["bg0"], "terminal.foreground": p["fg0"],
        "terminalCursor.foreground": p["purple"],
        "terminal.ansiBlack": a[0], "terminal.ansiRed": a[1], "terminal.ansiGreen": a[2],
        "terminal.ansiYellow": a[3], "terminal.ansiBlue": a[4], "terminal.ansiMagenta": a[5],
        "terminal.ansiCyan": a[6], "terminal.ansiWhite": a[7],
        "terminal.ansiBrightBlack": a[8], "terminal.ansiBrightRed": a[9],
        "terminal.ansiBrightGreen": a[10], "terminal.ansiBrightYellow": a[11],
        "terminal.ansiBrightBlue": a[12], "terminal.ansiBrightMagenta": a[13],
        "terminal.ansiBrightCyan": a[14], "terminal.ansiBrightWhite": a[15],
    }
    tok = [
        (["comment", "punctuation.definition.comment"], p["fg1"], "italic"),
        (["string", "string.quoted", "constant.other.symbol"], p["green"], None),
        (["constant.numeric", "constant.numeric.integer", "constant.numeric.float"], p["orange"], None),
        (["constant.language", "constant.character", "support.constant"], p["yellow"], None),
        (["variable.other.constant", "entity.name.constant"], p["yellow"], None),
        (["keyword", "keyword.control", "storage", "storage.type", "storage.modifier"], p["blue"], None),
        (["keyword.operator"], p["op"], None),
        (["entity.name.function", "meta.function-call", "support.function"], p["purple"], None),
        (["entity.name.type", "entity.name.class", "support.type", "support.class"], p["cyan"], None),
        (["variable", "meta.definition.variable"], p["var"], None),
        (["variable.parameter"], p["param"], None),
        (["variable.other.property", "meta.object-literal.key"], p["var"], None),
        (["punctuation", "meta.brace", "punctuation.separator", "punctuation.terminator"], p["fg1"], None),
        (["entity.name.tag"], p["purple"], None),
        (["entity.other.attribute-name"], p["orange"], None),
        (["markup.heading", "entity.name.section"], p["blue"], "bold"),
        (["markup.bold"], p["fg0"], "bold"),
        (["markup.italic"], p["fg0"], "italic"),
        (["markup.inserted", "markup.inline.raw"], p["green"], None),
        (["markup.deleted"], p["red"], None),
        (["invalid", "invalid.illegal"], p["red"], None),
    ]
    token_colors = []
    for scopes, color, style in tok:
        settings = {"foreground": color}
        if style:
            settings["fontStyle"] = style
        token_colors.append({"scope": scopes, "settings": settings})
    theme = {"name": f"datum {mode}", "type": mode,
             "semanticHighlighting": True, "colors": ui, "tokenColors": token_colors}
    return json.dumps(theme, indent=2) + "\n"


# ---------------------------------------------------------------- bat (.tmTheme plist)
def bat(mode):
    p = pal(mode)
    rules = [
        ("comment", p["fg1"], "italic"),
        ("string", p["green"], None),
        ("constant.numeric", p["orange"], None),
        ("constant.language, constant.character, support.constant", p["yellow"], None),
        ("keyword, storage", p["blue"], None),
        ("keyword.operator", p["op"], None),
        ("entity.name.function, support.function", p["purple"], None),
        ("entity.name.type, entity.name.class, support.type", p["cyan"], None),
        ("variable", p["var"], None),
        ("variable.parameter", p["param"], None),
        ("punctuation", p["fg1"], None),
        ("entity.name.tag", p["purple"], None),
        ("invalid", p["red"], None),
    ]
    body = [
        "    <dict>",
        "      <key>settings</key>",
        "      <dict>",
        f"        <key>background</key><string>{p['bg0']}</string>",
        f"        <key>foreground</key><string>{p['fg0']}</string>",
        f"        <key>caret</key><string>{p['purple']}</string>",
        f"        <key>selection</key><string>{p['bg2']}</string>",
        f"        <key>lineHighlight</key><string>{p['bg1']}</string>",
        "      </dict>",
        "    </dict>",
    ]
    for scope, color, style in rules:
        body.append("    <dict>")
        body.append(f"      <key>scope</key><string>{scope}</string>")
        body.append("      <key>settings</key>")
        body.append("      <dict>")
        body.append(f"        <key>foreground</key><string>{color}</string>")
        if style:
            body.append(f"        <key>fontStyle</key><string>{style}</string>")
        body.append("      </dict>")
        body.append("    </dict>")
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n<dict>\n'
        f"  <key>name</key><string>datum-{mode}</string>\n"
        "  <key>settings</key>\n  <array>\n" + "\n".join(body) + "\n  </array>\n"
        "</dict>\n</plist>\n"
    )


# ---------------------------------------------------------------- iterm2 (.itermcolors plist)
def _rgb01(h):
    h = h.lstrip("#")
    return [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]


def iterm(mode):
    """iTerm2 .itermcolors -- the source format for the iTerm2-Color-Schemes repo,
    the upstream that feeds many terminals' built-in theme pickers. Submitted there
    as a one-off manual PR; generated here so it never drifts from the palette."""
    p, a = pal(mode), ansi16(mode)
    colors = {f"Ansi {i} Color": a[i] for i in range(16)}
    colors.update({
        "Background Color": p["bg0"], "Foreground Color": p["fg0"], "Bold Color": p["fg0"],
        "Cursor Color": p["purple"], "Cursor Text Color": p["bg0"], "Cursor Guide Color": p["bg1"],
        "Selection Color": p["bg2"], "Selected Text Color": p["fg0"],
        "Link Color": p["blue"], "Badge Color": p["red"],
    })
    order = [f"Ansi {i} Color" for i in range(16)] + [
        "Background Color", "Bold Color", "Cursor Color", "Cursor Guide Color",
        "Cursor Text Color", "Foreground Color", "Link Color", "Selected Text Color",
        "Selection Color", "Badge Color"]

    def entry(key):
        r, g, b = _rgb01(colors[key])
        return (f"  <key>{key}</key>\n  <dict>\n"
                "    <key>Color Space</key><string>sRGB</string>\n"
                f"    <key>Red Component</key><real>{r}</real>\n"
                f"    <key>Green Component</key><real>{g}</real>\n"
                f"    <key>Blue Component</key><real>{b}</real>\n"
                "    <key>Alpha Component</key><real>1</real>\n  </dict>")

    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n'
        # XML comments can't contain "--", so no shared GEN marker here.
        f"<!-- datum-{mode} : generated by tools/gen_ports.py from tools/derive.py; do not edit by hand -->\n"
        "<dict>\n" + "\n".join(entry(k) for k in order) + "\n</dict>\n</plist>\n"
    )


# ---------------------------------------------------------------- registry
def _per_mode(app, fn, ext):
    return {f"ports/{app}/datum-{m}.{ext}": (lambda m=m: fn(m)) for m in MODES}


PORTS = {}
PORTS.update({f"ports/ghostty/datum-{m}": (lambda m=m: ghostty(m)) for m in MODES})
PORTS.update(_per_mode("alacritty", alacritty, "toml"))
PORTS.update(_per_mode("kitty", kitty, "conf"))
PORTS.update(_per_mode("wezterm", wezterm, "toml"))
# VS Code themes live inside the extension folder so `vsce package` / a symlink
# into ~/.vscode/extensions makes them installable (see ports/vscode/package.json).
PORTS.update({f"ports/vscode/themes/datum-{m}.json": (lambda m=m: vscode(m)) for m in MODES})
PORTS.update(_per_mode("bat", bat, "tmTheme"))
# iTerm2 scheme files — not applied locally; generated for the upstream PR to
# iTerm2-Color-Schemes (feeds Ghostty/WezTerm/Kitty/Alacritty built-in pickers).
PORTS.update(_per_mode("iterm", iterm, "itermcolors"))
PORTS["ports/tmux/datum.tmux"] = tmux_theme
PORTS["ports/fzf/datum.sh"] = fzf_theme
PORTS["ports/delta/datum.gitconfig"] = delta_theme
PORTS["ports/shell/datum.sh"] = shell_theme


def main():
    check = "--check" in sys.argv
    stale = []
    for rel, render in sorted(PORTS.items()):
        path = os.path.join(ROOT, rel)
        content = render()
        current = open(path).read() if os.path.exists(path) else None
        if check:
            if current != content:
                stale.append(rel)
            continue
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(content)
        print(("unchanged " if current == content else "wrote     ") + rel)
    if check:
        print("STALE: " + ", ".join(stale) if stale else "all ports up to date")
        return 1 if stale else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
